# Send mentor Request
POST http://localhost:5000/mentor_request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ4MzQ5NjYxfQ.-xYPSbN3bo1D3HycKDj_SdspBEKZtO44fr9PJ2Vrpt8

{
  "mentorId": "68359e91f4cd4582350acdd0",
  "userId": "6835b9e5346da0f557f98d9d",
  "numberOfMentees": 2,
  "residentialArea": "Kito Amenu",
  "message": "Looking for academic guidance"
}

### 

# Get mentor request by Id
GET http://localhost:5000/mentor_request/6836cf72eed75cb61b476415
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ4MzQ5NjYxfQ.-xYPSbN3bo1D3HycKDj_SdspBEKZtO44fr9PJ2Vrpt8

### 

# Change request Status

PUT http://localhost:5000/mentor_request/6836d2deeecefe0c62cea87c/rejected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ4MzQ5NjYxfQ.-xYPSbN3bo1D3HycKDj_SdspBEKZtO44fr9PJ2Vrpt8